package com.bank.islamic.incomepurification;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Income Purification
 *
 * Business Area:      Shariah Governance and Compliance
 * Business Domain:    Shariah Governance
 * Functional Pattern: Process
 * Asset Type:         Purification Entry
 * Control Record:     Purification Entry Procedure
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Income Purification — BIAN Semantic API")
                .description("Service Domain 'Income Purification' (Process pattern) "
                        + "operating on the 'Purification Entry Procedure' control record.")
                .version("0.1.0"));
    }
}
